// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: internal/server/servertest/golden/golden.proto

package golden

import (
	client "github.com/achew22/toy-project/internal/server/servertest/client"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestStepIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor string          `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Rpc   *client.Request `protobuf:"bytes,2,opt,name=rpc,proto3" json:"rpc,omitempty"`
}

func (x *TestStepIn) Reset() {
	*x = TestStepIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_servertest_golden_golden_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestStepIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStepIn) ProtoMessage() {}

func (x *TestStepIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_servertest_golden_golden_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStepIn.ProtoReflect.Descriptor instead.
func (*TestStepIn) Descriptor() ([]byte, []int) {
	return file_internal_server_servertest_golden_golden_proto_rawDescGZIP(), []int{0}
}

func (x *TestStepIn) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *TestStepIn) GetRpc() *client.Request {
	if x != nil {
		return x.Rpc
	}
	return nil
}

type TestStepOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rpc *client.Response `protobuf:"bytes,1,opt,name=rpc,proto3" json:"rpc,omitempty"`
}

func (x *TestStepOut) Reset() {
	*x = TestStepOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_servertest_golden_golden_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestStepOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStepOut) ProtoMessage() {}

func (x *TestStepOut) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_servertest_golden_golden_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStepOut.ProtoReflect.Descriptor instead.
func (*TestStepOut) Descriptor() ([]byte, []int) {
	return file_internal_server_servertest_golden_golden_proto_rawDescGZIP(), []int{1}
}

func (x *TestStepOut) GetRpc() *client.Response {
	if x != nil {
		return x.Rpc
	}
	return nil
}

var File_internal_server_servertest_golden_golden_proto protoreflect.FileDescriptor

var file_internal_server_servertest_golden_golden_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x67, 0x6f, 0x6c,
	0x64, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x26, 0x63, 0x6d, 0x64, 0x2e, 0x61, 0x63, 0x68, 0x65, 0x77, 0x2e, 0x74, 0x6f, 0x79, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x1a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x74, 0x65, 0x73, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x65, 0x70, 0x49, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x36, 0x0a, 0x03,
	0x72, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6d, 0x64, 0x2e,
	0x61, 0x63, 0x68, 0x65, 0x77, 0x2e, 0x74, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x03, 0x72, 0x70, 0x63, 0x22, 0x46, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53, 0x74, 0x65, 0x70,
	0x4f, 0x75, 0x74, 0x12, 0x37, 0x0a, 0x03, 0x72, 0x70, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x61, 0x63, 0x68, 0x65, 0x77, 0x2e, 0x74, 0x6f, 0x79,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x72, 0x70, 0x63, 0x42, 0x49, 0x5a, 0x47,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x68, 0x65, 0x77,
	0x32, 0x32, 0x2f, 0x74, 0x6f, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e,
	0x3b, 0x67, 0x6f, 0x6c, 0x64, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_server_servertest_golden_golden_proto_rawDescOnce sync.Once
	file_internal_server_servertest_golden_golden_proto_rawDescData = file_internal_server_servertest_golden_golden_proto_rawDesc
)

func file_internal_server_servertest_golden_golden_proto_rawDescGZIP() []byte {
	file_internal_server_servertest_golden_golden_proto_rawDescOnce.Do(func() {
		file_internal_server_servertest_golden_golden_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_server_servertest_golden_golden_proto_rawDescData)
	})
	return file_internal_server_servertest_golden_golden_proto_rawDescData
}

var file_internal_server_servertest_golden_golden_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_server_servertest_golden_golden_proto_goTypes = []any{
	(*TestStepIn)(nil),      // 0: cmd.achew.toyproject.servertest.golden.TestStepIn
	(*TestStepOut)(nil),     // 1: cmd.achew.toyproject.servertest.golden.TestStepOut
	(*client.Request)(nil),  // 2: cmd.achew.toyproject.api.v1.Request
	(*client.Response)(nil), // 3: cmd.achew.toyproject.api.v1.Response
}
var file_internal_server_servertest_golden_golden_proto_depIdxs = []int32{
	2, // 0: cmd.achew.toyproject.servertest.golden.TestStepIn.rpc:type_name -> cmd.achew.toyproject.api.v1.Request
	3, // 1: cmd.achew.toyproject.servertest.golden.TestStepOut.rpc:type_name -> cmd.achew.toyproject.api.v1.Response
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_server_servertest_golden_golden_proto_init() }
func file_internal_server_servertest_golden_golden_proto_init() {
	if File_internal_server_servertest_golden_golden_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_server_servertest_golden_golden_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TestStepIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_servertest_golden_golden_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TestStepOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_server_servertest_golden_golden_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_server_servertest_golden_golden_proto_goTypes,
		DependencyIndexes: file_internal_server_servertest_golden_golden_proto_depIdxs,
		MessageInfos:      file_internal_server_servertest_golden_golden_proto_msgTypes,
	}.Build()
	File_internal_server_servertest_golden_golden_proto = out.File
	file_internal_server_servertest_golden_golden_proto_rawDesc = nil
	file_internal_server_servertest_golden_golden_proto_goTypes = nil
	file_internal_server_servertest_golden_golden_proto_depIdxs = nil
}
