// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: internal/server/servertest/client/client.proto

package client

import (
	v1 "github.com/achew22/toy-project/api/v1"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*Request_GreetRequest
	Request isRequest_Request `protobuf_oneof:"request"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_servertest_client_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_servertest_client_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_server_servertest_client_client_proto_rawDescGZIP(), []int{0}
}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *Request) GetGreetRequest() *v1.GreetRequest {
	if x, ok := x.GetRequest().(*Request_GreetRequest); ok {
		return x.GreetRequest
	}
	return nil
}

type isRequest_Request interface {
	isRequest_Request()
}

type Request_GreetRequest struct {
	GreetRequest *v1.GreetRequest `protobuf:"bytes,1,opt,name=greet_request,json=greetRequest,proto3,oneof"`
}

func (*Request_GreetRequest) isRequest_Request() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*Response_Status
	//	*Response_GreetResponse
	Response isResponse_Response `protobuf_oneof:"response"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_servertest_client_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_servertest_client_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_server_servertest_client_client_proto_rawDescGZIP(), []int{1}
}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *Response) GetStatus() *status.Status {
	if x, ok := x.GetResponse().(*Response_Status); ok {
		return x.Status
	}
	return nil
}

func (x *Response) GetGreetResponse() *v1.GreetResponse {
	if x, ok := x.GetResponse().(*Response_GreetResponse); ok {
		return x.GreetResponse
	}
	return nil
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_Status struct {
	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type Response_GreetResponse struct {
	GreetResponse *v1.GreetResponse `protobuf:"bytes,2,opt,name=greet_response,json=greetResponse,proto3,oneof"`
}

func (*Response_Status) isResponse_Response() {}

func (*Response_GreetResponse) isResponse_Response() {}

var File_internal_server_servertest_client_client_proto protoreflect.FileDescriptor

var file_internal_server_servertest_client_client_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1b, 0x63, 0x6d, 0x64, 0x2e, 0x61, 0x63, 0x68, 0x65, 0x77, 0x2e, 0x74, 0x6f, 0x79, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x66, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x0d, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x61, 0x63, 0x68, 0x65, 0x77, 0x2e, 0x74, 0x6f,
	0x79, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c,
	0x67, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x99, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x53, 0x0a, 0x0e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6d, 0x64,
	0x2e, 0x61, 0x63, 0x68, 0x65, 0x77, 0x2e, 0x74, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x72, 0x65, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x63, 0x68, 0x65, 0x77, 0x32, 0x32, 0x2f, 0x74, 0x6f, 0x79, 0x2d, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x74, 0x65, 0x73, 0x74,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x3b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_server_servertest_client_client_proto_rawDescOnce sync.Once
	file_internal_server_servertest_client_client_proto_rawDescData = file_internal_server_servertest_client_client_proto_rawDesc
)

func file_internal_server_servertest_client_client_proto_rawDescGZIP() []byte {
	file_internal_server_servertest_client_client_proto_rawDescOnce.Do(func() {
		file_internal_server_servertest_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_server_servertest_client_client_proto_rawDescData)
	})
	return file_internal_server_servertest_client_client_proto_rawDescData
}

var file_internal_server_servertest_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_server_servertest_client_client_proto_goTypes = []any{
	(*Request)(nil),          // 0: cmd.achew.toyproject.api.v1.Request
	(*Response)(nil),         // 1: cmd.achew.toyproject.api.v1.Response
	(*v1.GreetRequest)(nil),  // 2: cmd.achew.toyproject.api.v1.GreetRequest
	(*status.Status)(nil),    // 3: google.rpc.Status
	(*v1.GreetResponse)(nil), // 4: cmd.achew.toyproject.api.v1.GreetResponse
}
var file_internal_server_servertest_client_client_proto_depIdxs = []int32{
	2, // 0: cmd.achew.toyproject.api.v1.Request.greet_request:type_name -> cmd.achew.toyproject.api.v1.GreetRequest
	3, // 1: cmd.achew.toyproject.api.v1.Response.status:type_name -> google.rpc.Status
	4, // 2: cmd.achew.toyproject.api.v1.Response.greet_response:type_name -> cmd.achew.toyproject.api.v1.GreetResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_server_servertest_client_client_proto_init() }
func file_internal_server_servertest_client_client_proto_init() {
	if File_internal_server_servertest_client_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_server_servertest_client_client_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_servertest_client_client_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_server_servertest_client_client_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_GreetRequest)(nil),
	}
	file_internal_server_servertest_client_client_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Status)(nil),
		(*Response_GreetResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_server_servertest_client_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_server_servertest_client_client_proto_goTypes,
		DependencyIndexes: file_internal_server_servertest_client_client_proto_depIdxs,
		MessageInfos:      file_internal_server_servertest_client_client_proto_msgTypes,
	}.Build()
	File_internal_server_servertest_client_client_proto = out.File
	file_internal_server_servertest_client_client_proto_rawDesc = nil
	file_internal_server_servertest_client_client_proto_goTypes = nil
	file_internal_server_servertest_client_client_proto_depIdxs = nil
}
